import data_preparation
import single_var_analysis

single_var_analysis.response_rate(data_preparation.df_all)
single_var_analysis.frequency(data_preparation.df_yes)
single_var_analysis.purchase_location(data_preparation.df_yes)
single_var_analysis.brand_known_for(data_preparation.df_yes)
single_var_analysis.receipt(data_preparation.df_yes)
